import request from '@/utils/request'
const schema = {
  // 用户平台接口
  frontend: {
    'search': '/match',
    'map': '/map',
    'region': '/region',
    'country': '/country',
    'user-login': '/user/login',
    'user-register': '/user/register',
    'dashboard-revenue': '/dashboard/summary_revenue',
    'dashboard-offers': '/dashboard/my_offers',
    'dashboard-performance': '/dashboard/performance',
    'dashboard-payout': '/dashboard/payout',
    'user-logout': '/user/logout',
    'offer-list': '/offer/list',
    'offer-detail': '/offer/detail',
    'user-send-email': '/user/password/email',
    'user-password-reset': '/user/password/reset',
    'account-settings': '/account/settings',
    'account-settings-update': '/account/settings/update',
    'account-password-update': '/user/password/update',
    'account-billing': '/account/billing',
    'account-billing-update': '/account/billing/update',
    'domain-list': '/domain/list',
    'domain-update': '/domain/update',
    'payout-list': '/payout/list',
    'payout-detail': '/payout/detail',
    'postback-create': '/postback/create',
    'postback-list': '/postback/list',
    'postback-change-status': '/postback/change_status',
    'postback-save_global': '/postback/save_global',
    'postback-detail_global': '/postback/global_detail',
    'postback-delete': '/postback/delete',
    'report-summary': '/reports/summary',
    'reports-order': '/reports/order',
    'reports-bonus': '/reports/bonus',
  },
  
  // 用户管理后台接口
  backend: {
    'search': '/match',
    'map': '/map',
    'region': '/region',
    'country': '/country',
    'user-login': '/admin/login',
    'admin-password-update': '/admin/password/reset',
    'dashboar-conversion': '/dashboard/summary_conversion',
    'dashboard-cost': '/dashboard/cost',
    'dashboard-performance': '/dashboard/performance',
    'user-logout': '/admin/logout',
    'offer-list': '/offer/list',
    'offer-page_list': '/offer/page_list',
    'offer-detail': '/offer/detail',
    'offer-update': '/offer/update',
    'offer-batch': '/offer/batch_status',
    'creative-list': '/creative/list', //后台独有的,
    'creative-save': '/creative/update',
    'creative-remove': '/creative/delete',
    'creative-batch': '/creative/batch_status',
    'member-list': '/user/list',
    'member-save': '/user/create',
    'member-update': '/user/update',
    'member-detail': '/user/detail',
    'member-password-reset': '/user/password_update',
    'billing-list': '/billing/list',
    'billing-batch-status': '/billing/batch_status',
    'billing-detail': '/billing/detail',
    'reports-preview': '/billing/preview',
    'billing-update': '/billing/update',
    'billing-delete': '/billing/delete',
    'affiliate-list': '/affiliate/list',
    'affiliate-detail': '/affiliate/detail',
    'affiliate-create': '/affiliate/create',
    'affiliate-update': '/affiliate/update',
    'affiliate-payout-offers': '/affiliate/payout_offers',
    'affiliate-batch-status': '/affiliate/batch_status',
    'domain-list': '/domain/list',
    'domain-update': '/domain/update',
    'report-summary': '/reports/summary',
    'reports-order': '/reports/order',
    'reports-bonus': '/reports/bonus',
    'reports-bonus-create': '/reports/bonus/create',
    'reports-billing-create': '/reports/billing/generate',
  }
}

export default function (method) {
  let prefixion = /admin/g.test(window.location.pathname) ? 'backend' : 'frontend'
  return data => request(`/${prefixion}${schema[prefixion][method]}`, data) 
}
